CREATE TABLE lims_barcode (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   uuid VARCHAR(255) NOT NULL,
   manifest_id VARCHAR(255),
   sample_id VARCHAR(255),
   test_id INTEGER,
   serial_number INTEGER,
   CONSTRAINT pk_lims_barcode PRIMARY KEY (id)
);

ALTER TABLE lims_barcode ADD CONSTRAINT uc_lims_barcode_uuid UNIQUE (uuid);